djcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (LoginView, LogoutView, PasswordResetView,
                                       PasswordResetDoneView, PasswordResetConfirmView,
                                       PasswordResetCompleteView)
from django.urls import include, path
from leads.views import landing_page, LandingPageView, SignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", LandingPageView.as_view(), name= "landing-page"),
    path("leads/", include("leads.urls", namespace="leads")),
    path("agents/", include("agents.urls", namespace="agents")),
    path("login/",LoginView.as_view(), name="login"),
    path("logout/",LogoutView.as_view(), name="logout"),
    path("signup/",SignupView.as_view(), name="signup"),
    path("reset-password/",PasswordResetView.as_view(), name="reset_password"),
    path("password-reset-done/",PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("password-reset-confirm/<uidb64>/<token>/",PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("password_reset_complete", PasswordResetCompleteView.as_view(), name= "password_reset_complete")
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from leads.views import ( list_leads,lead_detail, create_lead,lead_update,lead_delete,
                        LeadListView, LeadDetailView, LeadCreateView, LeadUpdateView, LeadDeleteView, AssignAgentView, CategoryListView, CategoryDetailView, CategoryUpdateView, CategoryCreateView, CategoryUpdateViewCategory,CategoryDeleteViewCategory
)

app_name = "leads"

urlpatterns = [
    path("", LeadListView.as_view(), name= "lead-list"),
    path("create/", LeadCreateView.as_view(), name="lead-create"),
    path("<int:pk>/details/", LeadDetailView.as_view(), name="lead-detail"),
    path("<int:pk>/update/", LeadUpdateView.as_view(), name="lead-update"),
    path("<int:pk>/delete/", LeadDeleteView.as_view(), name="lead-delete"),
    path("<int:pk>/assign-agent/", AssignAgentView.as_view(), name= "assign-agent"),
    path("categories/", CategoryListView.as_view(), name= "category-list"),
    path("category/<int:pk>/details/", CategoryDetailView.as_view(), name= "category-detail"),
    path("lead-category/<int:pk>/update/", CategoryUpdateView.as_view(), name= "category-update"),
    path("category/create/", CategoryCreateView.as_view(), name= "category-create"),
    path("category/<int:pk>/update/", CategoryUpdateViewCategory.as_view(), name= "category-update-category"),
    path("category/<int:pk>/delete/", CategoryDeleteViewCategory.as_view(), name= "category-delete-category")
]

leads/models.py
from operator import le
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
# Create your models here.

class User(AbstractUser):
    is_organiser = models.BooleanField(default=True)
    is_agent = models.BooleanField(default=False)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Lead(models.Model):
    first_name = models.CharField(max_length= 50)
    last_name = models.CharField(max_length= 50)
    age = models.IntegerField(default=0)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    agent = models.ForeignKey("Agent", on_delete=models.SET_NULL, blank=True, null=True)
    category = models.ForeignKey("Category",related_name="leads", on_delete = models.CASCADE,null=True, blank=True)
    description = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    phone_number = models.CharField(max_length=20)
    email = models.EmailField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Category(models.Model):
    name = models.CharField(max_length=30)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
  


def userprofile_after_usersave(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(userprofile_after_usersave, sender= User)

leads/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField
from .models import Agent, Lead, Category

User = get_user_model()

class LeadModelForm(forms.ModelForm):
    class Meta:
        model= Lead
        fields=(
            "first_name",
            "last_name",
            "age",
            "agent",
            "description",
            "phone_number",
            "email",
        )


class Leadform(forms.Form):
    first_name= forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    age= forms.IntegerField(min_value=0)


class CustomUserCreateForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",)
        field_classes = {"username": UsernameField}


class LeadAssignFrom(forms.Form):
    agent = forms.ModelChoiceField(queryset=Agent.objects.none())

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request")
        queryset = Agent.objects.filter( organisation = request.user.userprofile )
        super(LeadAssignFrom, self).__init__(*args, **kwargs)
        self.fields["agent"].queryset = queryset


class LeadCategoryUpdateForm(forms.ModelForm):
    class Meta:
        model= Lead
        fields=(
            "category",
        )

    
class CategoryCreateFrom(forms.ModelForm):
    class Meta:
        model = Category
        fields=(
            "name",
        )

leads/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from agents.mixins import OrganizerAndLoginRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import redirect, render, reverse
from django.views import generic

from .forms import CustomUserCreateForm, LeadModelForm, LeadAssignFrom, LeadCategoryUpdateForm, CategoryCreateFrom
from .models import Category, Lead

class AssignAgentView(OrganizerAndLoginRequiredMixin, generic.FormView):
    template_name = "leads/assign_agent.html"
    form_class = LeadAssignFrom

    def get_form_kwargs(self, **kwargs):
        kwargs = super(AssignAgentView, self).get_form_kwargs(**kwargs)
        kwargs.update({
            'request': self.request
        })
        return kwargs

    def get_success_url(self):
        return reverse("leads:lead-list")
    
    def  form_valid(self,form):
        agent = form.cleaned_data["agent"]
        lead = Lead.objects.get(pk=self.kwargs["pk"])
        lead.agent = agent
        lead.save()
        return super(AssignAgentView, self).form_valid(form)
    

class SignupView(generic.CreateView):
    template_name = 'registration/signup.html'
    form_class= CustomUserCreateForm

    def get_success_url(self):
        return reverse("login")


class LandingPageView(generic.TemplateView):
    template_name = "landing.html"


def landing_page(request):
    return render(request, "landing.html")


class LeadListView(OrganizerAndLoginRequiredMixin, generic.ListView):
    template_name = "leads/all_leads.html"
    context_object_name = "leads" # by default the context name is object_list but we can override this

    def get_queryset(self):
        user = self.request.user
        if( user.is_organiser ):
            queryset = Lead.objects.filter(
                organisation = user.userprofile,
                agent__isnull=False
            )
        else:
            queryset = Lead.objects.filter(
                organisation = user.agent.organisation,
                agent__isnull=False
            )
            queryset.filter(agent__user = user)
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super(LeadListView, self).get_context_data(**kwargs)
        user = self.request.user
        if( user.is_organiser ):
            queryset = Lead.objects.filter(
                organisation = user.userprofile,
                agent__isnull=True 
            )
            context.update({
                "unassigned_leads" : queryset
            })
        
        return context


def list_leads(request):
    leads = Lead.objects.all()
    contaxt = {
        'leads': leads
    }
    return render(request,"leads/all_leads.html",context=contaxt)


class LeadDetailView(OrganizerAndLoginRequiredMixin, generic.DetailView):
    template_name="leads/lead_detail.html"
    context_object_name='lead'

    def get_queryset(self):
        user = self.request.user
        if( user.is_organiser ):
            queryset = Lead.objects.filter( organisation = user.userprofile )
        else:
            queryset = Lead.objects.filter( organisation = user.agent.organisation )
            queryset.filter(agent__user = user)
        
        return queryset


def lead_detail(request,pk):
    lead = Lead.objects.get(id=pk)
    context = {
        "lead":lead
    }
    return render(request,"leads/lead_detail.html",context=context)


class LeadCreateView(OrganizerAndLoginRequiredMixin, generic.CreateView):
    template_name ="leads/create_lead.html"
    form_class= LeadModelForm

    def get_success_url(self) :
        return reverse("leads:lead-list")
    
    def form_valid(self,form):
        lead = form.save(commit=False)
        lead.organisation = self.request.user.userprofile
        lead.save()
        send_mail(
            subject="Hello",
            message="How are you doing",
            from_email="test@gmail.com",
            recipient_list=["test@gmail.com"]
        )
        return super(LeadCreateView,self).form_valid(form)
    

def create_lead(request):
    form =LeadModelForm()
    if( request.method == "POST"):
        form = LeadModelForm(request.POST);
        if(form.is_valid()):
            form.save()
            return redirect("/leads/")
    context = {
        "form": form
    }
    return render(request, "leads/create_lead.html", context=context)


class LeadUpdateView(OrganizerAndLoginRequiredMixin,generic.UpdateView):
    template_name ="leads/lead_update.html"
    form_class= LeadModelForm

    def get_queryset(self):
        user = self.request.user
        return Lead.objects.filter( organisation = user.userprofile )

    def get_success_url(self) :
        return reverse("leads:lead-list")


def lead_update(request, pk):
    lead = Lead.objects.get(pk= pk)
    form = LeadModelForm(instance=lead)
    if(request.method == "POST"):
        form = LeadModelForm(request.POST,instance=lead)
        if(form.is_valid()):
            form.save()
            return redirect("/leads/"+str(pk)+"/details")
    context= {
        "lead":lead,
        "form":form
    }
    return render(request, "leads/lead_update.html", context)


class LeadDeleteView(OrganizerAndLoginRequiredMixin,generic.DeleteView):
    template_name = "leads/lead-delete.html"
    def get_success_url(self):
        return reverse("leads:lead-list")
    
    def get_queryset(self):
        user = self.request.user
        return Lead.objects.filter( organisation = user.userprofile ) 


def lead_delete(request,pk):
    lead = Lead.objects.get(pk=pk);
    lead.delete()
    return redirect('/leads/')


class CategoryListView(LoginRequiredMixin, generic.ListView):
    template_name = "leads/category_list.html"
    context_object_name= "category_list"

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        user = self.request.user
        if(user.is_organiser):
            queryset = Lead.objects.filter(
                organisation=user.userprofile
            )
        else :
            queryset = Lead.objects.filter(
                organisation=user.agent.organisation
            )
        context.update({
            "unassigned_lead": queryset.filter(category__isnull=True).count()
        })
        return context

    def get_queryset(self):
        user = self.request.user
        if(user.is_organiser):
            queryset = Category.objects.filter(
                organisation=user.userprofile
            )
        else :
            queryset = Category.objects.filter(
                organisation= user.agent.organisation
            )
        return queryset

    
class CategoryDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "leads/category_details.html"
    context_object_name = "category"

    def get_queryset(self):
        user = self.request.user
        if(user.is_organiser):
            queryset = Category.objects.filter(
                organisation=user.userprofile
            )
        else :
            queryset = Category.objects.filter(
                organisation= user.agent.organisation
            )
        return queryset


class CategoryUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = "leads/category_update.html"
    form_class = LeadCategoryUpdateForm

    def get_queryset(self):
        user = self.request.user
        if( user.is_organiser ):
            queryset = Lead.objects.filter(
                organisation = user.userprofile
            )
        else:
            queryset = Lead.objects.filter(
                organisation = user.agent.organisation
            )
            queryset.filter(agent__user = user)
        return queryset

    def get_success_url(self):
        return reverse("leads:lead-detail", kwargs= {"pk":self.get_object().id})

class CategoryCreateView(OrganizerAndLoginRequiredMixin, generic.CreateView):
    template_name="leads/category-create.html"
    form_class= CategoryCreateFrom

    def get_success_url(self):
        return reverse("leads:category-list")

    def form_valid(self, form):
        category = form.save(commit=False)
        category.organisation = self.request.user.userprofile
        category.save()
        return super(CategoryCreateView, self).form_valid(form)
    
class CategoryUpdateViewCategory(OrganizerAndLoginRequiredMixin, generic.UpdateView):
    template_name= "leads/category-update-cat.html"
    form_class= CategoryCreateFrom

    def get_queryset(self):
        user = self.request.user
        if(user.is_organiser):
            queryset = Category.objects.filter(
                organisation=user.userprofile
            )
        else :
            queryset = Category.objects.filter(
                organisation= user.agent.organisation
            )
        return queryset

    def get_success_url(self):
        return reverse("leads:category-detail", kwargs= {"pk":self.get_object().id})

class CategoryDeleteViewCategory(OrganizerAndLoginRequiredMixin, generic.DeleteView):
    template_name= "leads/category-delete-cat.html"

    def get_queryset(self):
        user = self.request.user
        if(user.is_organiser):
            queryset = Category.objects.filter(
                organisation=user.userprofile
            )
        else :
            queryset = Category.objects.filter(
                organisation= user.agent.organisation
            )
        return queryset

    def get_success_url(self):
        return reverse("leads:category-list")

leads/templates/leads/all_leads.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% block content %}
<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
      <div class= "flex justify-between items-center w-full mb-6 py-6 border-b  border-blue-800">
        <div>
          <h2 class ="text-3xl text-gray-800">Leads</h2>
          <a href= "{% url 'leads:category-list' %}" class="text-blue-500 hover:text-blue-800">View Categories</a>
        </div> 
        <div>
          <a href= "{% url 'leads:lead-create' %}" class="text-blue-500 hover:text-blue-800">Create new lead</a>
        </div> 
      </div>
      <div class="flex flex-wrap -m-4 ">
        {% for lead in leads %}
          <div class="p-4  md:w-full lg:w-1/2">
            <div class="flex border-2 rounded-lg border-lime-300 p-8 sm:flex-row flex-col">
              <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10" viewBox="0 0 24 24">
                    <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
                    <circle cx="12" cy="7" r="4"></circle>
                </svg>
              </div>
              <div class="flex-grow">
                <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
                  {{ lead.first_name}} {{ lead.last_name}}
                </h2>
                <p class="leading-relaxed text-base">
                  {{ lead.description }}
                </p>
                <a href= "{% url 'leads:lead-detail' lead.id %} " class="mt-3 text-indigo-500 inline-flex items-center">Lead Details
                  <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                    <path d="M5 12h14M12 5l7 7-7 7"></path>
                  </svg>
                </a>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
      {% if unassigned_leads.exists %}
        <div class= "flex justify-between items-center w-full mb-6 py-6 border-b  border-blue-800">
            <h2 class ="text-3xl text-gray-800">Unassigned Leads</h2> 
        </div>
        <div class="flex flex-wrap -m-4 ">
          {% for lead in unassigned_leads %}
            <div class="p-4 lg:w-1/2 md:w-full">
              <div class="flex border-2 rounded-lg border-lime-300 p-8 sm:flex-row flex-col">
                <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                  <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10" viewBox="0 0 24 24">
                      <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
                      <circle cx="12" cy="7" r="4"></circle>
                  </svg>
                </div>
                <div class="flex-grow">
                  <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{ lead.first_name}} {{ lead.last_name}} </h2>
                  <p class="leading-relaxed text-base">{{ lead.description }}</p>
                  <a href= "{% url 'leads:assign-agent' lead.id %} " class="mt-3 text-indigo-500 inline-flex items-center">Assign Lead
                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                      <path d="M5 12h14M12 5l7 7-7 7"></path>
                    </svg>
                  </a>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      {% endif %}
    </div>
  </section>
  {% endblock content %}

leads/templates/leads/assign_agent.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% block content %}
<div class = "max-w-lg mx-auto">
    <div class="border-b-2 mb-4">
        <a href= "{% url 'leads:lead-list' %}" class="underline font-medium" >Back</a>
    </div>
    <div class="text-center mb-4">
        <h3 class="text-2xl">Assign Lead to an agent</h3>
    </div>
    <form method="post" action= "">
        {% csrf_token %}
        {{ form|crispy }}
        <button type ="submit" class="w-full text-lg mt-2 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded mb-3 text-center">Submit</button>
    </form>
</div>
{% endblock content %}

leads/templates/leads/category-create.html
{% extends 'base.html' %}

{% load tailwind_filters %}
{% block content %}

<div class="max-w-lg mx-auto">
  <div class ="mb-4 border-b-2">
    <a class= "underline font-medium" href= "{% url 'leads:category-list' %}">Back</a>
  </div>
  <div class="mt-4 mb-4 text-center">
    <h2 class="text-2xl">Create new category</h2>
  </div>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy}}
    <button type="submit" class= "w-full text-lg mt-2 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded mb-3 text-center">Submit</button>
  </form>
</div>

{% endblock content %}

leads/templates/leads/category_details.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% block content %}


<section class="text-gray-600 body-font">
    <div class="container px-5  mx-auto">
      <div class="flex flex-col text-center w-full mb-20">
        <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">
            {{ category.name }}
        </h1>
        <p class="lg:w- mx-auto leading-relaxed text-base">
            Here are all types of lead categories under this category.
        </p>
        <div class= "mt-3 mb-3 ">
          <a href="{% url 'leads:category-update-category' category.pk %}" class= "text-lg mt-2 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded mb-3 text-center">Update</a>
          <a href="{% url 'leads:category-delete-category' category.pk %}" class ="text-lg mt-2 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded mb-3 text-center">Delete</a>
        </div>
      </div>
      <div class="lg:w-2/3 w-full mx-auto overflow-auto">
        <div class = "max-auto border-b-2  mb-5">
          <a href = "{% url 'leads:category-list' %}" class ="underline font-medium ">Back</a>
        </div>
        <table class="table-auto w-full text-left whitespace-no-wrap">
          <thead>
            <tr>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">
                First Name
              </th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">
                Last Name
              </th>
            </tr>
          </thead>
          <tbody>
            {% for lead in category.leads.all %}
              <tr>
                <td class="border-t-2 border-gray-200 px-4 py-3">
                  <a class = "hover:text-blue-800" href= "{% url 'leads:lead-detail' lead.pk %}">
                    {{ lead.first_name }}
                  </a>
                </td>
                <td class="border-t-2 border-gray-200 px-4 py-3">
                  {{ lead.last_name}}
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </section>
{% endblock content %}

leads/templates/leads/category_update.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <a href= "{% url 'leads:lead-list' %}" class= "underline font-medium">Back</a>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
            {{ lead.first_name}} {{ lead.last_name}}
          </h1>
          <div class="flex mb-4">
            <a href= "{% url 'leads:lead-detail' lead.id %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                Lead Details
            </a>
            <a href= "{% url 'leads:category-update' lead.id %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
              Category
            </a>
            <a href= "{% url 'leads:lead-update' lead.id %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update</a>
          </div>
          <form method="post" action= "">
            {% csrf_token %}
            {{ form | crispy }}
            <button type ="submit" class="w-full text-lg mt-2 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded mb-3 text-center" >Submit</button>
          </form>
        </div>
        <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
      </div>
    </div>
  </section>


{% endblock content %}

leads/templates/leads/lead_detail.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <a href= "{% url 'leads:lead-list' %}" class= "underline font-medium">Back</a>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
            {{ lead.first_name}} {{ lead.last_name}}
          </h1>
          <div class="flex mb-4">
            <a href= "{% url 'leads:lead-detail' lead.id %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                Lead Details
            </a>
            <a href= "{% url 'leads:category-update' lead.id %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
              Category
            </a>
            <a href= "{% url 'leads:lead-update' lead.id %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
              Update
            </a>
          </div>
          <p class="leading-relaxed mb-4">
            {{ leads.description }}
          </p>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Age</span>
            <span class="ml-auto text-gray-900">{{ lead.age }}</span>
          </div>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Email</span>
            <span class="ml-auto text-gray-900">{{ lead.email }}</span>
          </div>
          <div class="flex border-t border-b mb-6 border-gray-200 py-2">
            <span class="text-gray-500">Contact</span>
            <span class="ml-auto text-gray-900">{{ lead.phone_number }} </span>
          </div>
          <div class="flex flex-row-reverse mt-3">
            <a href="{% url 'leads:lead-update' lead.id%} " class="w-1/2 text-white bg-indigo-500 px-6 hover:bg-indigo-600 py-3 rounded text-center font-medium">Edit Details</a>
          </div>
        </div>
        <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
      </div>
    </div>
  </section>

{% endblock content %}

leads/templates/leads/lead_update.html
{% extends 'base.html' %}
{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest"><a href= "{% url 'leads:lead-list' %} ">Lead</a></h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
            {{ lead.first_name}} {{ lead.last_name}}
          </h1>
          <div class="flex mb-4">
            <a href= "{% url 'leads:lead-detail' lead.id %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                Lead Details
            </a>
            <a href= "{% url 'leads:lead-update' lead.id %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Update</a>
          </div>
          <form method="post" action= "">
            {% csrf_token %}
            {{ form.as_p }}
            <button type ="submit" class="w-1/3 flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded mb-3 text-center" >Submit</button>
          </form>
          <div class="flex">
            <button class="w-1/3 flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded"><a href= "{% url 'leads:lead-delete' lead.id %} ">Delete</a></button>
          </div>
        </div>
        <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
      </div>
    </div>
  </section>


{% endblock content %}