agents/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView, AgentDetailView,AgentDeleteView, AgentUpdateView

app_name = "agents"

urlpatterns = [
    path("", AgentListView.as_view(), name= "agent-list"),
    path("create/", AgentCreateView.as_view(), name= "agent-create"),
    path("<int:pk>/details/", AgentDetailView.as_view(), name="agent-detail"),
    path("<int:pk>/update/", AgentUpdateView.as_view(), name="agent-update"),
    path("<int:pk>/delete/", AgentDeleteView.as_view(), name="agent-delete"),
]

djcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (LoginView, LogoutView, PasswordResetView,
                                       PasswordResetDoneView, PasswordResetConfirmView,
                                       PasswordResetCompleteView)
from django.urls import include, path
from leads.views import landing_page, LandingPageView, SignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", LandingPageView.as_view(), name= "landing-page"),
    path("leads/", include("leads.urls", namespace="leads")),
    path("agents/", include("agents.urls", namespace="agents")),
    path("login/",LoginView.as_view(), name="login"),
    path("logout/",LogoutView.as_view(), name="logout"),
    path("signup/",SignupView.as_view(), name="signup"),
    path("reset-password/",PasswordResetView.as_view(), name="reset_password"),
    path("password-reset-done/",PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("password-reset-confirm/<uidb64>/<token>/",PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("password_reset_complete", PasswordResetCompleteView.as_view(), name= "password_reset_complete")
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()

class AgentModelForm(forms.ModelForm):
    class Meta:
        model= User
        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
        )

agents/views.py
from django.shortcuts import reverse
from django.views import generic
from leads.models import Agent
from .mixins import OrganizerAndLoginRequiredMixin
from .forms import AgentModelForm
from django.core.mail import send_mail

# Create your views here.

class AgentListView(OrganizerAndLoginRequiredMixin,generic.ListView):
    template_name = "agents/agent_list.html"

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)


class AgentCreateView(OrganizerAndLoginRequiredMixin, generic.CreateView):
    template_name = "agents/agent_create.html"
    form_class = AgentModelForm

    def get_success_url(self):
        return reverse("agents:agent-list")
    
    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_organiser = False
        user.is_agent=True
        user.set_password("random")
        user.save()
        Agent.objects.create(
            user=user,
            organisation = self.request.user.userprofile
        )
        send_mail(
            subject="Invitation for Agent",
            message=f"Hello {user.username},\nTou are invited for agent.",
            from_email="admin@gmail.com",
            recipient_list=[user.email]
        )
        return super(AgentCreateView, self).form_valid(form)


class AgentUpdateView(OrganizerAndLoginRequiredMixin, generic.UpdateView):
    template_name = "agents/agent_update.html"
    form_class = AgentModelForm
    context_object_name = "agent"

    def get_success_url(self):
        return reverse("agents:agent-list")
    
    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)
    

class AgentDetailView(OrganizerAndLoginRequiredMixin, generic.DetailView):
    template_name = "agents/agent_detail.html"
    context_object_name = "agent"

    def get_queryset(self):
        return Agent.objects.all()


class AgentDeleteView(OrganizerAndLoginRequiredMixin, generic.DeleteView):
    template_name = "agents/agent_delete.html"


    def get_success_url(self):
        return reverse("agents:agent-list")
    
    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)

agents/templates/agents/agent_create.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
<div class = "max-w-lg mx-auto">
    <div class= "border-b-2 mb-2 py-2">
        <a href= "{% url 'agents:agent-list' %}" class="font-medium underline text-lg" >All Agents</a>
    </div>
    <div class="text-center">
        <h3 class= "text-2xl mb-5">
            Create a new Agent
        </h3>
    </div>
    <form method="post" action= "">
        {% csrf_token %}
        {{ form|crispy }}
        <button type ="submit" class= "mt-4 text-white text-xl w-full bg-blue-500 hover:bg-blue-800 px-3 py-2 rounded mb-2">Submit</button>
    </form>
</div>
{% endblock content %}

agents/templates/agents/agent_delete.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% block content %}
<div class= "max-w-lg mx-auto">
    <div class= "border-b-2 mb-2 py-2">
        <a href= "{% url 'agents:agent-detail' agent.id %}" class="font-medium underline text-lg" >
            Back
        </a>
    </div>
    <div class= "mt-4 mb-4">
        <h3 class= "text-xl">Are you sure to delete this agent?</h3>
    </div>
    <form method="post" action= "">
        {% csrf_token %}
        {{ form|crispy }}
        <button type ="submit"class = "text-white text-xl w-1/2 bg-blue-500 hover:bg-blue-800 px-3 py-1 rounded mb-2">Submit</button>
    </form>
</div>
{% endblock content %}

agents/templates/agents/agent_detail.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
            {{ agent.user.username}}
          </h1>
          <div class="flex mb-4">
            <a href= "{% url 'agents:agent-detail' agent.id %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                Agent Details
            </a>
            <a href= "{% url 'agents:agent-update' agent.id %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update</a>
          </div>
          <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Age</span>
            <span class="ml-auto text-gray-900">{{ "lead.age"}}</span>
          </div>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Location</span>
            <span class="ml-auto text-gray-900">{{ "Location" }}</span>
          </div>
          <div class="flex border-t border-b mb-6 border-gray-200 py-2">
            <span class="text-gray-500">Contact</span>
            <span class="ml-auto text-gray-900">{{ "+918791847872"}} </span>
          </div>
          <div class="flex flex-row-reverse mt-3">
            <a href="{% url 'agents:agent-update' agent.id%} " class="w-1/2 text-white bg-indigo-500 px-6 hover:bg-indigo-600 py-3 rounded text-center font-medium">Edit Details</a>
          </div>
        </div>
        <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
      </div>
    </div>
  </section>

{% endblock content %}

agents/templates/agents/agent_list.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% block content %}
<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
      <div class= "flex justify-between items-center w-full mb-6 py-6 border-b  border-blue-800">
        <div>
          <h2 class ="text-3xl text-gray-800">Agents</h2>
        </div> 
        <div>
          <a href= "{% url 'agents:agent-create' %}" class="text-blue-500 hover:text-blue-800">
            Create new agent
          </a>
        </div> 
      </div>
      <div class="flex flex-wrap -m-4 ">
        {% for agent in object_list %}
          <div class="p-4 lg:w-1/2 md:w-full">
            <div class="flex border-2 rounded-lg border-lime-300 p-8 sm:flex-row flex-col">
              <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10" viewBox="0 0 24 24">
                    <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
                    <circle cx="12" cy="7" r="4"></circle>
                </svg>
              </div>
              <div class="flex-grow">
                <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
                  {{ agent.user.username}}
                </h2>
                <p class="leading-relaxed text-base">
                  Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.
                </p>
                <a href= "{% url 'agents:agent-detail' agent.id%}" class="mt-3 text-indigo-500 inline-flex items-center">Agent Details
                  <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                    <path d="M5 12h14M12 5l7 7-7 7"></path>
                  </svg>
                </a>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </section>

{% endblock content %}

agents/templates/agents/agent_update.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
            {{ agent.user.username}}
          </h1>
          <div class="flex mb-4">
            <a href= "{% url 'agents:agent-detail' agent.id %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                Agent Details
            </a>
            <a href= "{% url 'agents:agent-update' agent.id %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Update</a>
          </div>
          <form method="post" action= "">
            {% csrf_token %}
            {{ form|crispy }}

            <div class ="flex w-full mt-5">
              <button type ="submit" class="w-1/2 text-white bg-indigo-500 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded mr-4" >Submit</button>
              <a href= "{% url 'agents:agent-delete' agent.id %} " class = "px-5 w-1/2 py-2 bg-indigo-500 rounded text-white text-center">Delete</a></button>
            </div>
          </form>
          <div class="flex">
          </div>
        </div>
        <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
      </div>
    </div>
  </section>


{% endblock content %}

agents/templates/agents/create_agent.html
{% extends 'base.html' %}
{% block content %}
    <a href= "{% url 'agents:agent-list' %}" >Back</a>
    <hr>
    <h3>Create a new Agent</h3>
    <form method="post" action= "">
        {% csrf_token %}
        {{ form.as_p }}
        <button type ="submit">Submit</button>
    </form>
{% endblock content %}