agents/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView, AgentDetailView,AgentDeleteView, AgentUpdateView

app_name = "agents"

urlpatterns = [
    path("", AgentListView.as_view(), name= "agent-list"),
    path("create/", AgentCreateView.as_view(), name= "agent-create"),
    path("<int:pk>/details/", AgentDetailView.as_view(), name="agent-detail"),
    path("<int:pk>/update/", AgentUpdateView.as_view(), name="agent-update"),
    path("<int:pk>/delete/", AgentDeleteView.as_view(), name="agent-delete"),
]

djcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (LoginView, LogoutView, PasswordResetView,
                                       PasswordResetDoneView, PasswordResetConfirmView,
                                       PasswordResetCompleteView)
from django.urls import include, path
from leads.views import landing_page, LandingPageView, SignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", LandingPageView.as_view(), name= "landing-page"),
    path("leads/", include("leads.urls", namespace="leads")),
    path("agents/", include("agents.urls", namespace="agents")),
    path("login/",LoginView.as_view(), name="login"),
    path("logout/",LogoutView.as_view(), name="logout"),
    path("signup/",SignupView.as_view(), name="signup"),
    path("reset-password/",PasswordResetView.as_view(), name="reset_password"),
    path("password-reset-done/",PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("password-reset-confirm/<uidb64>/<token>/",PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("password_reset_complete", PasswordResetCompleteView.as_view(), name= "password_reset_complete")
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from leads.views import ( list_leads,lead_detail, create_lead,lead_update,lead_delete,
                        LeadListView, LeadDetailView, LeadCreateView, LeadUpdateView, LeadDeleteView, AssignAgentView, CategoryListView, CategoryDetailView, CategoryUpdateView, CategoryCreateView, CategoryUpdateViewCategory,CategoryDeleteViewCategory
)

app_name = "leads"

urlpatterns = [
    path("", LeadListView.as_view(), name= "lead-list"),
    path("create/", LeadCreateView.as_view(), name="lead-create"),
    path("<int:pk>/details/", LeadDetailView.as_view(), name="lead-detail"),
    path("<int:pk>/update/", LeadUpdateView.as_view(), name="lead-update"),
    path("<int:pk>/delete/", LeadDeleteView.as_view(), name="lead-delete"),
    path("<int:pk>/assign-agent/", AssignAgentView.as_view(), name= "assign-agent"),
    path("categories/", CategoryListView.as_view(), name= "category-list"),
    path("category/<int:pk>/details/", CategoryDetailView.as_view(), name= "category-detail"),
    path("lead-category/<int:pk>/update/", CategoryUpdateView.as_view(), name= "category-update"),
    path("category/create/", CategoryCreateView.as_view(), name= "category-create"),
    path("category/<int:pk>/update/", CategoryUpdateViewCategory.as_view(), name= "category-update-category"),
    path("category/<int:pk>/delete/", CategoryDeleteViewCategory.as_view(), name= "category-delete-category")
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Hello Puran</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        <link href= "{% static 'css/style.css'%}" rel= "stylesheet"/>
        <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
    </head>
    <body >
        {% include "navbar.html" %}
        {% block content %}
        {% endblock content %}

        {% include 'script.html' %}
    </body>
</html>

templates/landing.html
{% extends 'base.html' %}

{% block content %}

<section class="text-gray-600 body-font">
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
      <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero" src="https://dummyimage.com/720x600">
      <div class="text-center lg:w-2/3 w-full">
        <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">DJ crm</h1>
        <p class="mb-8 leading-relaxed">Crm helps you you to mamage the leads</p>
        <div class="flex justify-center">
          {% comment %} <button class="w-1/2 items-center text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg"> {% endcomment %}
            <a href="{% url 'login'%} " class="w-1/2 text-white bg-indigo-500 px-6 hover:bg-indigo-600 py-3 rounded">Log in to your account</a>
          {% comment %} </button> {% endcomment %}
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

templates/navbar.html
<header class="text-gray-600 body-font background-gray">
    <div class="container background-gray mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
      <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
          <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
        </svg>
        <span class="ml-3 text-xl">DJCrm</span>
      </a>
      <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
        {% if not request.user.is_authenticated %}
        <a href= "/" class="mr-5 hover:text-gray-900">Home</a>
        <a href= "{% url 'signup' %}" class="mr-5 hover:text-gray-900">Signup</a>
        {% endif %}
      </nav>
      {% if request.user.is_authenticated %}
        <a href= "{% url 'leads:lead-list' %}" class="mr-5 hover:text-gray-900">Leads</a>
        {% if request.user.is_organiser %}
        <a href= "{% url 'leads:category-list' %}" class="mr-5 hover:text-gray-900">Categories</a>
          <a href= "{% url 'agents:agent-list' %}" class="mr-5 hover:text-gray-900">Agents</a>
        {% endif %}
        <a class="inline-flex items-center py-1 px-3 focus:outline-none rounded text-base mt-4 md:mt-0">
          Log in as:{{request.user.username}}
        </a>
        <a href="{% url 'logout'%}" class="inline-flex items-center py-1 px-3 focus:outline-none rounded text-base mt-4 md:mt-0">Logout
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
          stroke-width ="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
            <path d="M5 12h14M12 5l7 7-7 7"></path>
          </svg>
        </a>
      {% else %}
      <a href="{% url 'login'%}" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">Login
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
          <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
      </a>
      {% endif %}
    </div>
  </header>

templates/script.html
{% load static %}

<script src= "{% static 'js/script.js'%} "></script>